import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { Inter, Bree_Serif } from "next/font/google";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const bree_serif = Bree_Serif({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
	variable: "--font-bree-serif",
});

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${bree_serif.variable}`}
			a>
			<body className="relative">
				<Navbar />
				<div className="flex">
					<div className="mt-20 w-[1120px] m-auto ">{children}</div>
					{/* <Fixtures /> */}
				</div>

				<Footer />
			</body>
		</html>
	);
}
